[package]
name = "Todo"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = "0.16.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }